import { createTheme } from "@mui/material";

const theme = createTheme({
  palette: {
    primary: {
      main: "#B71C1C",
      light: "#E53935",
      dark: "#7F0000",
      contrastText: "#FFFFFF",
    },
    secondary: {
      main: "#FFA500",
      light: "#FF6659",
      dark: "#9A0007",
      contrastText: "#FFFFFF",
    },
    background: {
      default: "#FFEBEE",
      paper: "#FFFFFF",
    },
    text: {
      primary: "#666",
      secondary: "#757575",
      disabled: "#BDBDBD",
    },
  },
  typography: {
    fontFamily: "Arial, sans-serif",
    h1: {
      fontSize: "2rem",
      fontWeight: 700,
      lineHeight: 1.2,
      [`@media (min-width:600px)`]: { fontSize: "2.5rem" },
      [`@media (min-width:960px)`]: { fontSize: "3rem" },
      [`@media (min-width:1280px)`]: { fontSize: "3.5rem" },
      [`@media (min-width:1920px)`]: { fontSize: "4rem" },
    },
    h2: {
      fontSize: "1.75rem",
      fontWeight: 600,
      lineHeight: 1.3,
      [`@media (min-width:600px)`]: { fontSize: "2rem" },
      [`@media (min-width:960px)`]: { fontSize: "2.25rem" },
      [`@media (min-width:1280px)`]: { fontSize: "2.5rem" },
      [`@media (min-width:1920px)`]: { fontSize: "3rem" },
    },
    h3: {
      fontSize: "1.5rem",
      fontWeight: 600,
      lineHeight: 1.4,
      [`@media (min-width:600px)`]: { fontSize: "1.75rem" },
      [`@media (min-width:960px)`]: { fontSize: "2rem" },
      [`@media (min-width:1280px)`]: { fontSize: "2.25rem" },
      [`@media (min-width:1920px)`]: { fontSize: "2.5rem" },
    },
    h4: {
      fontSize: "1.25rem",
      fontWeight: 500,
      lineHeight: 1.4,
      [`@media (min-width:600px)`]: { fontSize: "1.5rem" },
      [`@media (min-width:960px)`]: { fontSize: "1.75rem" },
      [`@media (min-width:1280px)`]: { fontSize: "2rem" },
      [`@media (min-width:1920px)`]: { fontSize: "2.25rem" },
    },
    h5: {
      fontSize: "1.125rem",
      fontWeight: 500,
      lineHeight: 1.4,
      [`@media (min-width:600px)`]: { fontSize: "1.25rem" },
      [`@media (min-width:960px)`]: { fontSize: "1.5rem" },
      [`@media (min-width:1280px)`]: { fontSize: "1.75rem" },
      [`@media (min-width:1920px)`]: { fontSize: "2rem" },
    },
    h6: {
      fontSize: "1rem",
      fontWeight: 500,
      lineHeight: 1.4,
      [`@media (min-width:600px)`]: { fontSize: "1.125rem" },
      [`@media (min-width:960px)`]: { fontSize: "1.25rem" },
      [`@media (min-width:1280px)`]: { fontSize: "1.5rem" },
      [`@media (min-width:1920px)`]: { fontSize: "1.75rem" },
    },
    body1: {
      fontSize: "1rem",
      fontWeight: 400,
      lineHeight: 1.6,
      [`@media (min-width:600px)`]: { fontSize: "1.125rem" },
      [`@media (min-width:960px)`]: { fontSize: "1.25rem" },
      [`@media (min-width:1280px)`]: { fontSize: "1.375rem" },
      [`@media (min-width:1920px)`]: { fontSize: "1.5rem" },
    },
    body2: {
      fontSize: "0.875rem",
      fontWeight: 400,
      lineHeight: 1.6,
      [`@media (min-width:600px)`]: { fontSize: "1rem" },
      [`@media (min-width:960px)`]: { fontSize: "1.125rem" },
      [`@media (min-width:1280px)`]: { fontSize: "1.25rem" },
      [`@media (min-width:1920px)`]: { fontSize: "1.375rem" },
    },
    caption: {
      fontSize: "0.75rem",
      fontWeight: 400,
      lineHeight: 1.5,
      [`@media (min-width:600px)`]: { fontSize: "0.875rem" },
      [`@media (min-width:960px)`]: { fontSize: "1rem" },
      [`@media (min-width:1280px)`]: { fontSize: "1.125rem" },
      [`@media (min-width:1920px)`]: { fontSize: "1.25rem" },
    },
    overline: {
      fontSize: "0.75rem",
      fontWeight: 600,
      letterSpacing: "1.5px",
      textTransform: "uppercase",
      [`@media (min-width:600px)`]: { fontSize: "0.875rem" },
      [`@media (min-width:960px)`]: { fontSize: "1rem" },
      [`@media (min-width:1280px)`]: { fontSize: "1.125rem" },
      [`@media (min-width:1920px)`]: { fontSize: "1.25rem" },
    },
  },
});

export { theme };
